### ISSUE TITLE
Incorrect progress value

### ISSUE THREAD

**Issue by neSpecc** [codex-team/ajax#17]
I use code from example, when progress handler changes a document title.

When file is uploaded, there are `Infinity%` value

**Comment by talyguryn** [comment]
Can not reproduce:

![image](https://user-images.githubusercontent.com/15259299/56247024-2e5d0400-60ac-11e9-9707-1ce7fe156ddb.png)

Code:

```javascript
ajax.transport({
  url: '/uploadImage',
  accept: 'image/*',
  progress: function (percentage) {
    document.title = `${percentage}%`;
  },
  ratio: 95,
  fieldName: 'image'
})
  .then(successCallback)
  .catch(errorCallback);
```
